import Navbar from './components/Navbar/page'
import ReduxProvider from './components/ReduxProvider/page'
import './globals.css'
import { Inter} from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Redux Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </ReduxProvider>
    </html>
  )
}
